# TP1 — Elemento triangular 6 nodos (EFA)

**Optimización:** `K` en Float64; `B` precomputada en nodos; casos de carga comparten el mismo trabajo simbólico.

In [ ]:
using LinearAlgebra, Symbolics
@variables r s

numval(x) = Float64(real(Symbolics.value(x)))
numval_mat(M) = map(numval, M)

c

"""Matrices B (3×12) en nodos paramétricos; una vez por geometría."""
function mat_B_at_nodes(B, coords)
    [numval_mat(substitute(B, Dict(r => coords[i, 1], s => coords[i, 2]))) for i in axes(coords, 1)]
end

function apply_dirichlet!(K::AbstractMatrix{Float64})
    K[2, :] .= 0; K[:, 2] .= 0; K[2, 2] = 1
    K[3, :] .= 0; K[:, 3] .= 0; K[3, 3] = 1
    K[4, :] .= 0; K[:, 4] .= 0; K[4, 4] = 1
    return K
end

function solve_case(K::Matrix{Float64}, B_nodes::Vector{Matrix{Float64}}, C::AbstractMatrix{Float64}, R::AbstractVector{Float64})
    U = K \ R
    ε = zeros(3, 6)
    σ = zeros(3, 6)
    for i in 1:6
        mul!(view(ε, :, i), B_nodes[i], U)
        mul!(view(σ, :, i), C, view(ε, :, i))
    end
    @inbounds for i in eachindex(ε)
        abs(ε[i]) < 1e-8 && (ε[i] = 0.0)
    end
    @inbounds for i in eachindex(σ)
        abs(σ[i]) < 1e-8 && (σ[i] = 0.0)
    end
    return U, ε, σ
end

numval (generic function with 1 method)

In [2]:
ν = 0.3 # Coeficiente de Poisson
EM = 2.1E06 # Módulo de Young - kgf/cm^2
C = (EM / (1 - ν^2)) * [1 ν 0; ν 1 0; 0 0 (1 - ν) / 2] # Matriz de constantes elásticas (tensión plana)
C = Float64.(C) # ensamblaje y post-proceso en float

In [3]:
# Coordenadas globales (6 nodos)
NodalCoords = [0 0; 3 0; 1.5 3; 1.5 0; 2.25 1.5; 0.75 1.5]

# Coordenadas paramétricas de nodos (referencia) — una sola definición
PARAM_COORDS = [0 0; 1 0; 0 1; 1/2 0; 1/2 1/2; 0 1/2]

# Funciones de forma (triángulo 6 nodos)
h4 = 4 * r * (1 - r - s)
h5 = 4 * r * s
h6 = 4 * s * (1 - r - s)
h1 = 1 - r - s - 1/2 * h4 - 1/2 * h6
h2 = r - 1/2 * h4 - 1/2 * h5
h3 = s - 1/2 * h5 - 1/2 * h6

Dr = Differential(r)
Ds = Differential(s)

Differential(s, 1)

In [14]:
H = [h1 h2 h3 h4 h5 h6]
∇H = [transpose([expand_derivatives.(Dr(H[i])) for i in 1:6]); transpose([expand_derivatives.(Ds(H[i])) for i in 1:6])]
# (Opcional) mapeo x,y; no usado en el cálculo siguiente
# x = expand((H * NodalCoords[:, 1])[1])
# y = expand((H * NodalCoords[:, 2])[1])

2×6 Matrix{Num}:
 -1 + 2.0r - 2.0(1 - r - s) + 2.0s  …  4s                -4s
 -1 + 2.0r - 2.0(1 - r - s) + 2.0s     4r  4(1 - r - s) - 4s

In [5]:
# J - Jacobiano. Fundamentals of FEA, Koutromanos-pag.240 (ec.8.5.25)
J = expand.(∇H * NodalCoords) 

J_inv = inv(J) # Inversa del Jacobiano
J_det = det(J) # Determinante del Jacobiano
display(J)
display(J_inv)
display(J_det)

2×2 Matrix{Num}:
 3.0    0
 1.5  3.0

2×2 Matrix{Num}:
  0.333333       0.0
 -0.166667  0.333333

9.0

In [6]:
B1 = expand.( J_inv * ∇H)

B = expand.([B1[1,1] 0 B1[1,2] 0 B1[1,3] 0 B1[1,4] 0 B1[1,5] 0 B1[1,6] 0
    0 B1[2,1] 0 B1[2,2] 0 B1[2,3] 0 B1[2,4] 0 B1[2,5] 0 B1[2,6]
    B1[2,1] B1[1,1] B1[2,2] B1[1,2] B1[2,3] B1[1,3] B1[2,4] B1[1,4] B1[2,5] B1[1,5] B1[2,6] B1[1,6]])

3×12 Matrix{Num}:
   -1.0 + 1.33333r + 1.33333s  …                          0
                            0     1.33333 - 1.33333r - 2.0s
 -0.5 + 0.666667r + 0.666667s                     -1.33333s

In [7]:
#Cuadratura de Gauss para siete puntos de integración sobre dominios triangulares
r1 = 0.1012865073235
r2 = 0.7974269853531
r3 = r1
r4 = 0.4701420641051
r5 = r4
r6 = 0.0597158717898
r7 =  1/3

s1 = r1
s2 = r1
s3 = r2
s4 = r6
s5 = r4
s6 = r4
s7 = r7

w1 = 0.1259391805448
w2 = w1
w3 = w1
w4 = 0.1323941527885
w5 = w4
w6 = w4
w7 = 0.225

GL7T = [r1 s1; r2 s2; r3 s3; r4 s4; r5 s5; r6 s6; r7 s7] # Puntos de Gauss para integración
WGL7T = [w1 w2 w3 w4 w5 w6 w7]; # Pesos para  puntos de Gauss


In [ ]:
K = assemble_K!(B, J_det, GL7T, WGL7T, C)
display(K)

12×12 Matrix{Num}:
  1.25481e6    375000.0   3.50962e5      9615.38  …   -2.69231e5   -4.61538e5
   375000.0   6.92308e5    -9615.38      38461.5      -5.38462e5   -7.69231e5
  3.50962e5    -9615.38   1.25481e6    -375000.0     -2.03785e-7   4.65152e-8
    9615.38     38461.5   -375000.0    6.92308e5      4.36266e-8  -8.90286e-8
    67307.7   1.34615e5     67307.7   -1.34615e5      -2.69231e5   -5.38462e5
  1.15385e5   1.92308e5  -1.15385e5    1.92308e5  …   -4.61538e5   -7.69231e5
 -1.40385e6     38461.5  -1.40385e6     -38461.5      -5.38462e5        1.0e6
   -38461.5  -1.53846e5     38461.5   -1.53846e5           1.0e6   -1.53846e6
 3.83297e-8  1.14233e-8  -2.69231e5    5.38462e5      -2.80769e6  -8.36517e-8
 1.14669e-8  2.11439e-8   4.61538e5   -7.69231e5     -6.75718e-8   -3.07692e5
 -2.69231e5  -5.38462e5   -2.038e-7   4.36412e-8  …    3.88462e6  -2.90165e-8
 -4.61538e5  -7.69231e5   4.6537e-8  -8.90723e-8     -2.90165e-8    3.38462e6

In [9]:
# Condiciones de contorno Dirichlet + B en nodos (reutilizable en todos los casos)
apply_dirichlet!(K)
B_nodes = mat_B_at_nodes(B, PARAM_COORDS)
display(K)

12×12 Matrix{Num}:
  1.25481e6  0  0  0      67307.7    1.15385e5  …   -2.69231e5   -4.61538e5
          0  1  0  0            0            0               0            0
          0  0  1  0            0            0               0            0
          0  0  0  1            0            0               0            0
    67307.7  0  0  0    4.03846e5          0.0      -2.69231e5   -5.38462e5
  1.15385e5  0  0  0          0.0    1.15385e6  …   -4.61538e5   -7.69231e5
 -1.40385e6  0  0  0  -5.86733e-8  -1.74477e-8      -5.38462e5        1.0e6
   -38461.5  0  0  0  -2.03581e-8  -1.67813e-7           1.0e6   -1.53846e6
 3.83297e-8  0  0  0   -2.69231e5    4.61538e5      -2.80769e6  -8.36517e-8
 1.14669e-8  0  0  0    5.38462e5   -7.69231e5     -6.75718e-8   -3.07692e5
 -2.69231e5  0  0  0   -2.69231e5   -4.61538e5  …    3.88462e6  -2.90165e-8
 -4.61538e5  0  0  0   -5.38462e5   -7.69231e5     -2.90165e-8    3.38462e6

In [10]:
#= \(A,B)
Matrix division using a polyalgorithm. For input matrices A and B, the result X is such that A*X == B when A is square. 
The solver that is used depends upon the structure of A. If A is upper or lower triangular (or diagonal), no factorization 
of A is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, 
an LU factorization is used.
=#

In [11]:
# Casos de carga (kgf): mismo K y B_nodes; solo cambia R
cases = [
    (Float64[0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0], "Caso 1: F1=500, F2=0"),
    (Float64[0, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0], "Caso 2: F1=0, F2=500"),
    (Float64[0, 0, 0, 0, 500, 500, 0, 0, 0, 0, 0, 0], "Caso 3: F1=500, F2=500"),
]

for (R, title) in cases
    println("\n=== ", title, " ===")
    U, ε, σ = solve_case(K, B_nodes, C, R)
    display(U)
    display(ε)
    display(σ)
end

12-element Vector{Num}:
  0.0007142857142859177
                    0.0
                    0.0
                    0.0
   0.004821428571429653
 0.00017857142857164582
 0.00032142857142864893
 0.00017857142857155718
  0.0014553571428574362
 -0.0004732142857143255
  0.0014553571428574203
   0.000848214285714642

3×6 Matrix{Num}:
 -0.000285714  -0.000190476  0.000238095  …    2.38095e-5  -2.38095e-5
  0.000952381  -0.000809524  -7.14286e-5     -0.000440476  0.000440476
          0.0           0.0    0.0012381      0.000619048  0.000619048

3×6 Matrix{Num}:
    0.0  -1000.0   500.0  -500.0   -250.0   250.0
 2000.0  -2000.0     0.0     0.0  -1000.0  1000.0
    0.0      0.0  1000.0     0.0    500.0   500.0

In [12]:
# Caso 2 integrado en la celda anterior (vector `cases`).

3×6 Matrix{Num}:
 -0.000119048  -0.000119048   9.52381e-5  …   -1.19048e-5  -1.19048e-5
   3.57143e-5    3.57143e-5  0.000404762      0.000220238  0.000220238
  0.000619048  -0.000619048          0.0     -0.000309524  0.000309524

3×6 Matrix{Num}:
 -250.0  -250.0   500.0  -250.0   125.0  125.0
    0.0     0.0  1000.0     0.0   500.0  500.0
  500.0  -500.0     0.0     0.0  -250.0  250.0

In [13]:
# Caso 3 integrado en la celda anterior (vector `cases`).

3×6 Matrix{Num}:
 -0.000404762  -0.000309524  0.000333333  …    1.19048e-5  -3.57143e-5
  0.000988095   -0.00077381  0.000333333     -0.000220238  0.000660714
  0.000619048  -0.000619048    0.0012381      0.000309524  0.000928571

3×6 Matrix{Num}:
 -250.0  -1250.0  1000.0  -750.0  -125.0   375.0
 2000.0  -2000.0  1000.0     0.0  -500.0  1500.0
  500.0   -500.0  1000.0     0.0   250.0   750.0