In [1]:
using LinearAlgebra, Plots, LaTeXStrings, Symbolics

In [2]:
const E = 2.1E06
const ν = 0.3

global C = ((1 - ν) / ((1 + ν) * (1 - ν))) * E * [1 (ν/(1-ν)) 0; (ν/(1-ν)) 1 0; 0 0 ((1-2*ν)/(2*(1-ν)))];

In [3]:
const numNodosx = 3
const numNodosy = 3
const numNodosG = numNodosx * numNodosy

global GDLG = numNodosG * 2  # En el caso de elasticidad bidimensional se tiene 2 grados de libertad por nodo

const longx = 3.0
const longy = 3.0

const numElementos = (numNodosx - 1) * (numNodosy - 1);

In [4]:
begin
    @variables r s
    Dr = Differential(r)
    Ds = Differential(s)

    nFI = 4

    h₁ = 1 / 4 * (1 + r) * (1 + s)
    h₂ = 1 / 4 * (1 - r) * (1 + s)
    h₃ = 1 / 4 * (1 - r) * (1 - s)
    h₄ = 1 / 4 * (1 + r) * (1 - s)

    global H = [h₁ h₂ h₃ h₄]
    global ∇H = [transpose([expand_derivatives(Dr(H[i])) for i in 1:nFI]); transpose([expand_derivatives(Ds(H[i])) for i in 1:nFI])]
end

2×4 Matrix{Num}:
 0.25(1 + s)  -0.25(1 + s)  -0.25(1 - s)   0.25(1 - s)
 0.25(1 + r)   0.25(1 - r)  -0.25(1 - r)  -0.25(1 + r)

In [5]:
# Puntos de Gauss para itegración
nNodosInt = 9
GL9Q = [-sqrt(0.6) -sqrt(0.6); 0 -sqrt(0.6); sqrt(0.6) -sqrt(0.6); sqrt(0.6) 0; sqrt(0.6) sqrt(0.6);
    0 sqrt(0.6); -sqrt(0.6) sqrt(0.6); -sqrt(0.6) 0; 0 0]

wGL9Q = [5/9 5/9; 8/9 5/9; 5/9 5/9; 5/9 8/9; 5/9 5/9; 8/9 5/9; 5/9 5/9; 5/9 8/9; 8/9 8/9];

In [6]:
# Matriz de conectividad global para elementos bidimensionales de cuatro nodos 
#(El numero de elementos puede variar)
function matrizConectividadGlobal(numNodosx, numNodosy, numElementos)

    matrizConectividad = zeros(Int, numElementos, 4)
    elemento = 1

    for j in 1:numNodosy-1
        for i in 1:numNodosx-1
            nodoInferiorIzquierdo::Int = i + ((j - 1) * numNodosx)
            matrizConectividad[elemento, :] = [(nodoInferiorIzquierdo + numNodosx + 1) (nodoInferiorIzquierdo + numNodosx) nodoInferiorIzquierdo (nodoInferiorIzquierdo + 1)]
            elemento += 1
        end
    end

    return matrizConectividad
end

matrizConectividadGlobal (generic function with 1 method)

In [7]:
function mallador(numNodosx, numNodosy, longx, longy, numElementos)

    numSegmentosx = numNodosx - 1
    numSegmentosy = numNodosy - 1
    dNodosx = longx / numSegmentosx
    dNodosy = longy / numSegmentosy
    numNodosG = numNodosx * numNodosy
    matrizCoordG = zeros(numNodosG, 2)
    Coordy = 0
    nodo = 1

    for j in 1:numNodosy
        Coordx = 0
        for i in 1:numNodosx
            matrizCoordG[nodo, :] = [Coordx Coordy]
            Coordx += dNodosx
            nodo += 1
        end
        Coordy += dNodosy
    end

    return matrizCoordG
end

mallador (generic function with 1 method)

In [8]:
function matrizGdGL(numNodosx, numNodosy, mConectividadGlobal)

    numElementos = (numNodosx - 1) * (numNodosy - 1)
    numNodosGlobales = numNodosx * numNodosy
    mGdGL = zeros(Integer, 8, numElementos)

    for i in 1:numElementos
        j = 1
        while j <= 4
            zz = mConectividadGlobal[i, :]
            mGdGL[2*j-1, i] = zz[j] * 2 - 1
            mGdGL[2*j, i] = zz[j] * 2
            j += 1
        end
    end

    return mGdGL
end

matrizGdGL (generic function with 1 method)

In [9]:
begin
    mConectG = matrizConectividadGlobal(numNodosx, numNodosy, numElementos)
    #display(mConectG)
    mGdlG = matrizGdGL(numNodosx, numNodosy, mConectG)
    display(mGdlG)
    mGCoorNodales = mallador(numNodosx, numNodosy, longx, longy, numElementos)
    #display(mGCoorNodales)
end

8×4 Matrix{Integer}:
  9  11  15  17
 10  12  16  18
  7   9  13  15
  8  10  14  16
  1   3   7   9
  2   4   8  10
  3   5   9  11
  4   6  10  12

9×2 Matrix{Float64}:
 0.0  0.0
 1.5  0.0
 3.0  0.0
 0.0  1.5
 1.5  1.5
 3.0  1.5
 0.0  3.0
 1.5  3.0
 3.0  3.0

In [10]:
function Jacobiano(mGCoorNodales, mConectG, el)
    mNodalCoords = zeros(4, 2)
    for nodo in 1:4
        mNodalCoords[nodo, :] = mGCoorNodales[mConectG[el, :][nodo], :]
    end

    x₀ = expand((H*mNodalCoords[:, 1])[1])
    y₀ = expand((H*mNodalCoords[:, 2])[1])

    dxdr = expand_derivatives(Dr(x₀))
    dxds = expand_derivatives(Ds(x₀))
    dydr = expand_derivatives(Dr(y₀))
    dyds = expand_derivatives(Ds(y₀))

    J = [dxdr dydr; dxds dyds] # Jacobiano

    return J
end

Jacobiano (generic function with 1 method)

In [11]:
function BL0(∇H, J)
 
    B = inv(J) * ∇H

    BL0₁ = [B[1, 1] 0 B[1,2] 0 B[1,3] 0 B[1,4] 0]
    BL0₂ = [0 B[2,1] 0 B[2, 2] 0 B[2,3] 0 B[2,4]]
    BL0₃ = [B[2,1] B[1, 1] B[2, 2] B[1,2] B[2,3] B[1,3] B[2,4] B[1,4]]

    BL0 = vcat(BL0₁, BL0₂, BL0₃)

    return BL0
end

BL0 (generic function with 1 method)

In [12]:
function BL1(∇H, J, Uₑ)
    
    B = inv(J) * ∇H

    l₁₁, l₁₂, l₂₁, l₂₂ = 0, 0, 0, 0

    for k in 1:4 l₁₁ += B[1, k] * Uₑ[k, 1] end
    for k in 1:4 l₁₂ += B[2, k] * Uₑ[k, 1] end
    for k in 1:4 l₂₁ += B[1, k] * Uₑ[k, 2] end
    for k in 1:4 l₂₂ += B[2, k] * Uₑ[k, 2] end

    BL1₁ = [l₁₁ * B[1, 1] l₂₁ * B[1, 1] l₁₁ * B[1, 2] l₂₁ * B[1, 2] l₁₁ * B[1, 3] l₂₁ * B[1, 3] l₁₁ * B[1, 4] l₂₁ * B[1, 4]]
    BL1₂ = [l₁₂ * B[2, 1] l₂₂ * B[2, 1] l₁₂ * B[2, 2] l₂₂ * B[2, 2] l₁₂ * B[2, 3] l₂₂ * B[2, 3] l₁₂ * B[2, 4] l₂₂ * B[2, 4]]
    BL1₃ = [(l₁₁ * B[2, 1] + l₁₂ * B[1, 1]) (l₂₁ * B[2, 1] + l₂₂ * B[1, 1]) (l₁₁ * B[2, 2] + l₁₂ * B[1, 2]) (l₂₁ * B[2, 2] + l₂₂ * B[1, 2]) (l₁₁ * B[2, 3] + l₁₂ * B[1, 3]) (l₂₁ * B[2, 3] + l₂₂ * B[1, 3]) (l₁₁ * B[2, 4] + l₁₂ * B[1, 4]) (l₂₁ * B[2, 4] + l₂₂ * B[1, 4])]
    
    BL1 = vcat(BL1₁, BL1₂, BL1₃)

    return BL1
end

BL1 (generic function with 1 method)

In [31]:
# TDG -> Tensor Gradiente de Deformaciones
function TGD(Uₑ, J, mGCoorNodales, mConectG, el) # TDG -> TENSOR GRADIENTE DE DEFORMACIÓN
    X₁ = inv(J)
    mNodalCoordsₜ = zeros(4, 2)
    for nodo in 1:4
        mNodalCoordsₜ[nodo, :] = mGCoorNodales[mConectG[el, :][nodo], :] + Uₑ[nodo, :]
    end

    xₜ = expand((H*mNodalCoordsₜ[:, 1])[1])
    yₜ = expand((H*mNodalCoordsₜ[:, 2])[1])

    dxdrₜ = expand_derivatives(Dr(xₜ))
    dxdsₜ = expand_derivatives(Ds(xₜ))
    dydrₜ = expand_derivatives(Dr(yₜ))
    dydsₜ = expand_derivatives(Ds(yₜ))

    X₂ = [dxdrₜ dydrₜ; dxdsₜ dydsₜ]

    X = X₂ * X₁ # X -> TENSOR GRADIENTE DE DEFORMACIONES
    return X

end

TGD (generic function with 1 method)

In [14]:
# Matriz de Rigidez Global Lineal *******
function KGL0(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q)

    KGL0 = zeros(Float64, GDLG, GDLG)

    for el in 1:numElementos
        KEL = zeros(Float64, 8, 8)
        GLE = mGdlG[:, el]
        numGLE = length(GLE)
        
        J = Jacobiano(mGCoorNodales, mConectG, el)
        BL₀ = BL0(∇H, J)
        
        for i in 1:9 # Integración en los puntos de Gauss
            Jg_det = substitute(det(J), Dict([r => GL9Q[i, 1], s => GL9Q[i, 2]]))
            Bg = substitute(BL₀, Dict([r => GL9Q[i, 1], s => GL9Q[i, 2]]))
            KEL += (transpose(Bg) * C * Bg * Jg_det * wGL9Q[i, 1] * wGL9Q[i, 2])
        end

        for i in 1:numGLE
            for j in 1:numGLE
                KGL0[GLE[i], GLE[j]] += KEL[i, j].val
            end
        end
    end
    return KGL0
end

KGL0 (generic function with 1 method)

In [15]:
#RE = zeros(Number, GDLGlobales, numElementos)
RG = zeros(GDLG)
RG[18] = 3000
RG[14] = 3000
#RG[8] = 3000
#RG[6] = 3000
#RG = [0., 3000., 0., 3000., 0., 0., 0., 0.]
#display(RG)

3000

In [16]:
KGL = KGL0(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q);

In [17]:
# Caso 1 (1 elemento)

# Imponemos condiciones de contorno de Dirichlet
#=
# U1x=0 => U1=0
KG[1, :] .= 0
KG[:, 1] .= 0
KG[1, 1] = 1

# U1y=0 => U2=0
KG[2, :] .= 0
KG[:, 2] .= 0
KG[2, 2] = 1

# U2x=0 => U3=0
KG[3, :] .= 0
KG[:, 3] .= 0
KG[3, 3] = 1

# U2y=0 => U4=0
KG[4, :] .= 0
KG[:, 4] .= 0
KG[4, 4] = 1

display(KG)

U₀ = KGL \ RG # U₀ -> Desplazamientos en ⁰U 
=#

In [18]:
# Caso 2 (4 Elementos)
# Imponemos condiciones de contorno de Dirichlet

#
# U1x=0 => U1=0
KGL[1, :] .= 0
KGL[:, 1] .= 0
KGL[1, 1] = 1

# U1y=0 => U2=0
KGL[2, :] .= 0
KGL[:, 2] .= 0
KGL[2, 2] = 1

# U2x=0 => U3=0
KGL[3, :] .= 0
KGL[:, 3] .= 0
KGL[3, 3] = 1

# U2y=0 => U4=0
KGL[4, :] .= 0
KGL[:, 4] .= 0
KGL[4, 4] = 1

# U3x=0 => U5=0
KGL[5, :] .= 0
KGL[:, 5] .= 0
KGL[5, 5] = 1

# U3y=0 => U6=0
KGL[6, :] .= 0
KGL[:, 6] .= 0
KGL[6, 6] = 1

1

In [19]:
U = KGL \ RG

18-element Vector{Float64}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.00038012514028317975
  0.0024876583744940484
 -3.8883276355802194e-19
  0.0013895381141987445
 -0.00038012514028318035
  0.002487658374494048
  0.0023806785862530177
  0.007497264615256223
  8.325420909912773e-20
  0.0012774191848092266
 -0.0023806785862530177
  0.007497264615256221

In [32]:
# mGdlG <- matrix Grados de libertad global
function FGA(U)
    FG = zeros(Float64, GDLG)

    for el in 1:numElementos
        mGdlE = mGdlG[:, el]
        numGLE = length(mGdlE)
        
        Uₑ = transpose(reshape(U[mGdlE], 2, 4))
        Fₑ = zeros(8, 1)

        J = Jacobiano(mGCoorNodales, mConectG, el)

        BL₀ = BL0(∇H, J)
        BL₁ = BL1(∇H, J, Uₑ)
        BL = BL₀ + BL₁
        
        X = TGD(Uₑ, J, mGCoorNodales, mConectG, el) # TENSOR GRADIENTE DE DEFORMACIONES
    
        ϵ = 1 / 2 * (transpose(X) * X - Matrix(I, 2, 2)) # TENSOR DE DEFORMACIONES DE GREEN-LAGRANGE

        ϵv = [ϵ[1, 1]; ϵ[2, 2]; ϵ[1, 2]] # VECTOR DE DEFORMACIONES DE GREEN-LAGRANGE

        S = C * ϵv # S -> SEGUNDO TENSOR DE PIOLA KIRCHHOFF
        for i in 1:9
            Sₑₗ = substitute(S, Dict([r => GL9Q[i, 1], s => GL9Q[i, 2]]))
            BLₑ = substitute(BL, Dict([r => GL9Q[i, 1], s => GL9Q[i, 2]]))
            Fₑ += transpose(BLₑ) * Sₑₗ
        end

        for i in 1:numGLE # numGLE -> Grados de libertad del elemento
            FG[mGdlE[i]] += Fₑ[i]
        end
    end
    return FG
end

FGA (generic function with 1 method)

In [33]:
FGA(U)

18-element Vector{Float64}:
  -2188.4754768765183
  -6660.360106838713
      3.319655661471188e-10
 -10730.465803575866
   2188.47547687629
  -6660.360106838456
  -1162.1609818955326
  -1626.3907263619958
      8.833467290969566e-10
   3113.851689201206
   1162.1609818941374
  -1626.3907263621768
   1312.0073928475242
  11061.668975738656
      1.709850039333105e-10
   2066.7778292984503
  -1312.0073928472862
  11061.668975738889

In [21]:
function KGL1(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, U)
    KGL = zeros(Float64, GDLG, GDLG)

    for el in 1:numElementos
        KEL = zeros(Float64, 8, 8)
        mGdlE = mGdlG[:, el]
        numGLE = length(mGdlE)
        Uₑ = transpose(reshape(U[mGdlE], 2, 4))
        
        J = Jacobiano(mGCoorNodales, mConectG, el)
        BL₀ = BL0(∇H, J)
        BL₁ = BL1(∇H, J, Uₑ)
        BL = BL₀ + BL₁
        
        for i in 1:9 # Integración en los puntos de Gauss
            Jg_det = substitute(det(J), Dict([r => GL9Q[i, 1], s => GL9Q[i, 2]]))
            Bg = substitute(BL, Dict([r => GL9Q[i, 1], s => GL9Q[i, 2]]))
            KEL += (transpose(Bg) * C * Bg * Jg_det * wGL9Q[i, 1] * wGL9Q[i, 2])
        end

        for i in 1:numGLE
            for j in 1:numGLE
                KGL[mGdlE[i], mGdlE[j]] += KEL[i, j].val
            end
        end
    end
    return KGL
end

KGL1 (generic function with 1 method)

In [22]:
KGL1(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, U)

18×18 Matrix{Float64}:
 692298.0             2.88812e5  …       0.0              0.0
      2.88812e5       6.94155e5          0.0              0.0
     -4.61514e5  -57712.2                0.0              0.0
  57811.8             1.15683e5          0.0              0.0
      0.0             0.0                0.0              0.0
      0.0             0.0        …       0.0              0.0
      1.15355e5   57619.4                0.0              0.0
 -57913.8            -4.63e5             0.0              0.0
     -3.46139e5      -2.8872e5          -3.45133e5  -289324.0
     -2.8871e5       -3.46838e5         -2.89233e5       -3.48697e5
      0.0             0.0        …       1.15172e5    58600.5
      0.0             0.0           -56932.0             -4.64296e5
      0.0             0.0                0.0              0.0
      0.0             0.0                0.0              0.0
      0.0             0.0               -4.60203e5   -59544.8
      0.0             0.0        … 

In [23]:
function KGNL(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, U)
    KGNL = zeros(Float64, GDLG, GDLG)
    for el in 1:numElementos
        mGdlE = mGdlG[:, el]
        numGLE = length(mGdlE)
        KENL = zeros(numGLE, numGLE)
        Uₑ = transpose(reshape(U[mGdlE], 2, 4))

        J = Jacobiano(mGCoorNodales, mConectG, el)
        B = inv(J) * ∇H
        
        X = TGD(Uₑ, J, mGCoorNodales, mConectG, el) # TENSOR GRADIENTE DE DEFORMACIONES    
        ϵ = 1 / 2 * (transpose(X) * X - Matrix(I, 2, 2)) # TENSOR DE DEFORMACIONES DE GREEN-LAGRANGE
        ϵv = [ϵ[1, 1]; ϵ[2, 2]; ϵ[1, 2]] # VECTOR DE DEFORMACIONES DE GREEN-LAGRANGE
        S = C * ϵv # S -> SEGUNDO TENSOR DE PIOLA KIRCHHOFF
        ST = [S[1,1] S[3,1] 0 0; S[3,1] S[2,1] 0 0; 0 0 S[1,1] S[3,1]; 0 0 S[3,1] S[2,1]]

        BNL1 = [B[1,1] 0 B[1,2] 0 B[1,3] 0 B[1,4] 0]
        BNL2 = [B[2,1] 0 B[2,2] 0 B[2,3] 0 B[2,4] 0]
        BNL3 = [0 B[1,1] 0 B[1,2] 0 B[1,3] 0 B[1,4]]
        BNL4 = [0 B[2,1] 0 B[2,2] 0 B[2,3] 0 B[2,4]]
        BNL = vcat(BNL1, BNL2, BNL3, BNL4)

        for i in 1:9 # Integración en los puntos de Gauss
            BNLG = substitute(BNL, Dict([r => GL9Q[i, 1], s => GL9Q[i, 2]]))
            STG = substitute(ST, Dict([r => GL9Q[i, 1], s => GL9Q[i, 2]]))
            KENL += (transpose(BNLG) * STG * BNLG * wGL9Q[i, 1] * wGL9Q[i, 2])
        end

        for i in 1:numGLE
            for j in 1:numGLE
                KGNL[mGdlE[i], mGdlE[j]] += KENL[i, j]
            end
        end
        
    end

    return KGNL
    
end

KGNL (generic function with 1 method)

In [24]:
KGNL(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, U)

18×18 Matrix{Float64}:
  1816.13       0.0      114.423  …      0.0        0.0        0.0
     0.0     1816.13       0.0           0.0        0.0        0.0
   114.423      0.0     3026.64          0.0        0.0        0.0
     0.0      114.423      0.0           0.0        0.0        0.0
     0.0        0.0      114.423         0.0        0.0        0.0
     0.0        0.0        0.0    …      0.0        0.0        0.0
 -1181.89       0.0     -846.753         0.0        0.0        0.0
     0.0    -1181.89       0.0        -128.249      0.0        0.0
  -748.664      0.0    -1561.98          0.0     -853.737      0.0
     0.0     -748.664      0.0        -719.543      0.0     -853.737
     0.0        0.0     -846.753  …      0.0    -2229.94       0.0
     0.0        0.0        0.0        -128.249      0.0    -2229.94
     0.0        0.0        0.0           0.0        0.0        0.0
     0.0        0.0        0.0        1167.18       0.0        0.0
     0.0        0.0        0.0      

In [49]:
it = 0
KG = zeros(GDLG, GDLG)
RG = zeros(GDLG)
RG[18] = 3000
RG[14] = 3000
RA = zeros(GDLG)
Ui = U
ΔU = 0
#=
KG = KGL1(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, Ui) + KGNL(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, Ui)
display(KG)
display(RG)
RA = RG - FGA(Ui)
display(RA)
=#
while it <= 100
    #display(Ui)
    display(RG - FGA(Ui))
    KG = KGL1(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, Ui) + KGNL(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, Ui)
    RA = RG - FGA(Ui)
    RA = zeros(GDLG)
    RA[18] = 3000
    RA[14] = 3000
    #display(RA)

    KG[1, :] .= 0
    KG[:, 1] .= 0
    KG[1, 1] = 1

    # U1y=0 => U2=0
    KG[2, :] .= 0
    KG[:, 2] .= 0
    KG[2, 2] = 1

    # U2x=0 => U3=0
    KG[3, :] .= 0
    KG[:, 3] .= 0
    KG[3, 3] = 1

    # U2y=0 => U4=0
    KG[4, :] .= 0
    KG[:, 4] .= 0
    KG[4, 4] = 1

    # U3x=0 => U5=0
    KG[5, :] .= 0
    KG[:, 5] .= 0
    KG[5, 5] = 1

    # U3y=0 => U6=0
    KG[6, :] .= 0
    KG[:, 6] .= 0
    KG[6, 6] = 1   
    #display(KG)

    ΔU = KG \ RA
    Ui +=  ΔU    # OJO REVISAR CUIDADOSAMENTE
it += 1
end

18-element Vector{Float64}:
  2188.4754768765183
  6660.360106838713
    -3.319655661471188e-10
 10730.465803575866
 -2188.47547687629
  6660.360106838456
  1162.1609818955326
  1626.3907263619958
    -8.833467290969566e-10
 -3113.851689201206
 -1162.1609818941374
  1626.3907263621768
 -1312.0073928475242
 -8061.668975738656
    -1.709850039333105e-10
 -2066.7778292984503
  1312.0073928472862
 -8061.668975738889

18-element Vector{Float64}:
   4369.3344700830485
  13320.525461319892
     -9.094947017729282e-12
  21438.090501860504
  -4369.33447008304
  13320.525461319921
   2323.308516386266
   3270.6564341907833
     -1.0322764865122736e-10
  -6226.927254300072
  -2323.3085163862684
   3270.656434191611
  -2656.8392856243313
 -19106.6374129959
     -1.7007550923153758e-10
  -4180.252212590087
   2656.8392856246073
 -19106.637412996657

18-element Vector{Float64}:
   6542.698431603245
  19980.550816818708
      7.885319064371288e-10
  32123.090004603022
  -6542.698431603931
  19980.55081681904
   3483.436496196923
   4932.747993431738
      2.1582309273071587e-9
  -9339.265593394974
  -3483.436496199083
   4932.747993431596
  -4033.915645112003
 -30135.067618012115
      3.1650415621697903e-10
  -6340.28679568449
   4033.915645111584
 -30135.067618012516

18-element Vector{Float64}:
   8708.686925176095
  26640.49034260326
      7.894414011389017e-10
  42785.673973080666
  -8708.68692517678
  26640.490342603614
   4642.539440030979
   6612.615035329152
      1.889929990284145e-9
 -12450.906253452473
  -4642.539440033073
   6612.615035329167
  -5442.675570280627
 -41147.11432854969
      1.1295924196019769e-9
  -8546.74981839361
   5442.675570279601
 -41147.11432855009

18-element Vector{Float64}:
  10867.417686109431
  33300.39761312909
      2.764863893389702e-10
  53426.04607638767
 -10867.417686109813
  33300.39761312916
   5800.612448625881
   8310.206088756138
     -6.421032594516873e-10
 -15561.889361931255
  -5800.612448625229
   8310.206088755505
  -6882.576318321364
 -52142.92510940668
     -2.3646862246096134e-10
 -10799.513899413723
   6882.576318321698
 -52142.92510940589

18-element Vector{Float64}:
  13019.006678743794
  39960.325599329226
     -1.4551915228366852e-11
  64044.404233728535
 -13019.00667874378
  39960.32559932928
   6957.65116412409
  10025.468703659833
     -3.7471181713044643e-10
 -18672.255564405932
  -6957.651164123614
  10025.468703659411
  -8353.09239229691
 -63122.64072185675
     -1.2078089639544487e-9
 -13098.455831587211
   8353.092392298018
 -63122.64072185641

18-element Vector{Float64}:
  15163.568151686975
  46620.3266616645
      1.1641532182693481e-10
  74640.94084371877
 -15163.568151686999
  46620.32666166448
   8113.651732455034
  11758.34956284883
     -4.3655745685100555e-10
 -21782.045967740924
  -8113.651732455001
  11758.349562848292
  -9853.71468563651
 -74086.39546914217
     -2.6921043172478676e-10
 -15443.456386720432
   9853.714685637085
 -74086.39546914138

18-element Vector{Float64}:
  17301.214690939192
  53280.45254472778
      4.18367562815547e-10
  85215.8430016143
 -17301.21469093951
  53280.4525447281
   9268.610768492792
  13508.794583126051
      2.1009327610954642e-9
 -24891.30208831685
  -9268.610768495219
  13508.794583127521
 -11383.949679141146
 -85034.31751985442
      1.0986695997416973e-9
 -17834.400129296275
  11383.949679140269
 -85034.3175198562

18-element Vector{Float64}:
  19432.057271018617
  59940.75437321856
     -5.566107574850321e-10
  95769.29270528
 -19432.05727101817
  59940.754373218246
  10422.525323781138
  15276.749006776161
     -2.874003257602453e-10
 -28000.065804785263
 -10422.525323780552
  15276.749006777405
 -12943.3186865353
 -95966.52921099006
      2.837623469531536e-10
 -20271.175238503965
  12943.318686534816
 -95966.5292109911

18-element Vector{Float64}:
   21556.2053041768
   66601.2826491181
       8.658389560878277e-10
  106301.46705069969
  -21556.205304177565
   66601.28264911848
   11575.392856582079
   17062.157484219308
       1.9699655240401626e-9
  -31108.37931506357
  -11575.392856583965
   17062.157484220123
  -14531.357144974587
 -106883.14733217492
       8.149072527885437e-10
  -22753.67333796074
   14531.35714497358
 -106883.14733217646

18-element Vector{Float64}:
   23673.766687827614
   73262.08724993319
      -2.510205376893282e-10
  116812.53841769478
  -23673.766687827258
   73262.08724993315
   12727.21120413818
   18864.964148645973
       1.7025740817189217e-9
  -34216.285097065454
  -12727.2112041401
   18864.964148647006
  -16147.613947198628
 -117784.28339255237
       6.912159733474255e-10
  -25281.789332682813
   16147.613947198055
 -117784.2833925534

18-element Vector{Float64}:
   25784.847850232614
   79923.21742785597
       8.440110832452774e-10
  127302.67464651981
  -25784.84785023335
   79923.21742785622
   13877.978556890012
   20685.112683312822
       4.802132025361061e-10
  -37323.82587298159
  -13877.978556890703
   20685.112683312604
  -17791.650812337186
 -128670.04387158371
       8.003553375601768e-11
  -27855.42125270838
   17791.650812337215
 -128670.04387158374

18-element Vector{Float64}:
   27889.553794578886
   86584.72180974069
       5.4569682106375694e-11
  137772.03920592312
  -27889.553794578933
   86584.72180974073
   15027.693434570134
   22522.54638214523
       1.4915713109076023e-10
  -40431.04457668559
  -15027.693434570321
   22522.546382146917
  -19463.041692610073
 -139540.5304549838
       2.546585164964199e-10
  -30474.470103041822
   19463.04169260985
 -139540.5304549855

18-element Vector{Float64}:
   29987.98814147432
   93246.6483977864
      -5.093170329928398e-11
  148220.79135321308
  -29987.988141474165
   93246.64839778628
   16176.354663999873
   24377.208204222537
       6.402842700481415e-10
  -43537.984324055535
  -16176.35466400061
   24377.208204222858
  -21161.372213387807
 -150395.84025686834
       8.440110832452774e-10
  -33138.83971943855
   21161.37221338695
 -150395.84025686877

18-element Vector{Float64}:
   32080.253169972435
   99909.04457082713
       0.0
  158649.08628684757
  -32080.25316997243
   99909.04457082713
   17323.9613584544
   26249.04082265166
      -3.637978807091713e-11
  -46644.688385952584
  -17323.96135845445
   26249.040822651703
  -22886.239144318617
 -161236.06602909404
       4.3655745685100555e-11
  -35848.43662966459
   22886.239144318664
 -161236.06602909396

18-element Vector{Float64}:
   34166.449857174746
  106571.95708615324
       2.6193447411060333e-10
  169057.07529200334
  -34166.449857174906
  106571.9570861534
   18470.51289849587
   28137.98666833392
       1.8080754671245813e-9
  -49751.200163629765
  -18470.51289849756
   28137.986668333382
  -24637.24989937709
 -172061.29635873882
       4.3655745685100555e-10
  -38603.16991986979
   24637.24989937643
 -172061.2963587388

18-element Vector{Float64}:
   36246.67791647628
  113235.43208178657
       0.0
  179444.9058795714
  -36246.67791647627
  113235.43208178655
   19616.00891416773
   30043.98796901427
      -7.8580342233181e-10
  -52857.56316635675
  -19616.0089141672
   30043.987969012727
  -26414.022063880682
 -182871.6158545251
      -5.384208634495735e-10
  -41402.95110576647
   26414.02206388149
 -182871.6158545232

18-element Vector{Float64}:
   38321.035834520204
  119899.51507913652
       7.275957614183426e-11
  189812.72191895355
  -38321.03583452028
  119899.51507913657
   20760.44926842129
   31966.98678404186
       6.111804395914078e-10
  -55963.82099109163
  -20760.449268421813
   31966.986784041874
  -28216.182946691133
 -193667.10532297165
      -2.6921043172478676e-10
  -44247.69400827533
   28216.182946691293
 -193667.10532297185

18-element Vector{Float64}:
   40389.620906911725
  126564.25098598698
      -4.0745362639427185e-10
  200160.66376506205
  -40389.62090691141
  126564.25098598668
   21903.83404173713
   33906.92503517782
      -1.418811734765768e-9
  -59070.017304004316
  -21903.834041735394
   33906.925035178196
  -30043.369155911787
 -204447.84193499802
       1.4551915228366852e-10
  -47137.31463339124
   30043.36915591143
 -204447.84193499817

18-element Vector{Float64}:
   42452.52927274627
  133229.68409975042
       0.0
  210488.86837983562
  -42452.52927274626
  133229.68409975042
   23046.163517795598
   35863.7445337805
       1.709850039333105e-10
  -62176.195823698436
  -23046.163517795776
   35863.74453378111
  -31895.2261965801
 -215213.89938360374
       1.8917489796876907e-10
  -50071.731055991564
   31895.226196579933
 -215213.89938360435

18-element Vector{Float64}:
   44509.85594800629
  139895.85811095114
       0.0
  220797.46944861385
  -44509.85594800629
  139895.85811095114
   24187.43817017899
   37837.38700465183
      -1.709850039333105e-10
  -65282.40030602622
  -24187.43817017839
   37837.38700465066
  -33771.408088924894
 -225965.34803324335
      -5.238689482212067e-10
  -53050.86330730651
   33771.408088924996
 -225965.34803324257

18-element Vector{Float64}:
   46561.694857864444
  146562.8161068779
       2.4010660126805305e-10
  231086.59749166574
  -46561.69485786458
  146562.81610687813
   25327.65864997985
   39827.79410683722
       7.130438461899757e-10
  -68388.67453032987
  -25327.65864998084
   39827.79410683547
  -35671.57700588883
 -236702.2550614439
      -9.74978320300579e-10
  -56074.63326587854
   35671.577005889936
 -236702.2550614422

18-element Vector{Float64}:
   48608.13886794875
  153230.60057539487
       5.093170329928398e-11
  241356.37997113456
  -48608.13886794879
  153230.60057539487
   26466.825774304496
   41834.907451607956
      -4.001776687800884e-11
  -71495.06228697141
  -26466.82577430425
   41834.90745160755
  -37595.40292870004
 -247424.68459319574
      -3.346940502524376e-10
  -59142.96455177723
   37595.402928700176
 -247424.6845931954

18-element Vector{Float64}:
   50649.27981459842
  159899.2534088398
       6.548361852765083e-11
  251606.94139366932
  -50649.27981459837
  159899.2534088398
   27604.940515558657
   43858.668617859395
       8.731149137020111e-10
  -74601.60736611336
  -27604.940515559745
   43858.66861785995
  -39542.56331938551
 -258132.69782856098
       9.89530235528946e-10
  -62255.782423832294
   39542.56331938464
 -258132.6978285616

18-element Vector{Float64}:
   52685.20853416383
  166568.81590801405
       1.1132215149700642e-9
  261838.4034089725
  -52685.20853416482
  166568.81590801448
   28742.00399150035
   45899.01916512594
       1.69893610291183e-9
  -77708.35354755256
  -28742.003991502228
   45899.019165125675
  -41512.74280917884
 -268826.3531639642
       7.566995918750763e-10
  -65413.01367977129
   41512.74280917817
 -268826.3531639645

18-element Vector{Float64}:
   54716.01489138378
  173239.32878621639
      -4.3655745685100555e-11
  272050.8849045199
  -54716.01489138374
  173239.32878621636
   29878.01745599608
   47955.9006443962
       6.366462912410498e-10
  -80815.34459161678
  -29878.017455996887
   47955.90064439771
  -43505.63290186883
 -279505.7063075534
       3.4924596548080444e-10
  -68614.58655902161
   43505.632901868645
 -279505.70630755473

18-element Vector{Float64}:
   56741.78780686019
  179910.8321732914
      -2.1827872842550278e-11
  282244.5020966
  -56741.78780686017
  179910.83217329136
   31012.98229041193
   50029.254606931325
       2.473825588822365e-10
  -83922.62423095328
  -31012.982290412194
   50029.254606931936
  -45520.931691185644
 -290170.8103890261
       3.055902197957039e-10
  -71860.43064803982
   45520.93169118535
 -290170.81038902677

18-element Vector{Float64}:
   58762.61528369609
  186583.36561969802
       0.0
  292419.3686179547
  -58762.61528369608
  186583.36561969804
   32146.899995639033
   52119.022611192806
       1.1932570487260818e-9
  -87030.236163191
  -32146.899995640022
   52119.022611193446
  -47558.3435914019
 -300821.7160642521
       1.0040821507573128e-9
  -75150.47678804086
   47558.34359140071
 -300821.71606425307

18-element Vector{Float64}:
   60778.584433296186
  193256.96810054197
       1.4551915228366852e-11
  302575.59560211713
  -60778.5844332962
  193256.968100542
   33279.772184671005
   54225.14622808239
       2.9831426218152046e-10
  -90138.22404436141
  -33279.772184671485
   54225.146228084195
  -49617.579080372954
 -311458.47161503247
       9.89530235528946e-10
  -78484.65698493956
   49617.57908037213
 -311458.47161503433

18-element Vector{Float64}:
   62789.78150037714
  199931.67801958264
      -5.820766091346741e-11
  312713.2917646808
  -62789.78150037708
  199931.6780195826
   34411.60057571626
   56347.567044589174
       6.184563972055912e-10
  -93246.63148303924
  -34411.60057571683
   56347.56704458868
  -51698.35445430444
 -322081.1230442904
       2.6193447411060333e-10
  -81862.90432140429
   51698.3544543041
 -322081.12304429

18-element Vector{Float64}:
   64796.29188721466
  206607.53321319123
      -3.2014213502407074e-10
  322832.5634816415
  -64796.29188721444
  206607.53321319097
   35542.386985817415
   58486.22666596592
      -1.8917489796876907e-9
  -96355.50203514118
  -35542.386985815334
   58486.226665965165
  -53800.391593563225
 -332689.7141669662
       1.1641532182693481e-10
  -85285.15287088227
   53800.39159356302
 -332689.7141669651

18-element Vector{Float64}:
   66798.2001771534
  213284.57095423495
       2.9103830456733704e-11
  332933.51486496406
  -66798.20017715331
  213284.57095423483
   36672.133324913855
   60641.06671658822
       3.4924596548080444e-10
  -99464.87919931831
  -36672.133324914175
   60641.066716587695
  -55923.417738926815
 -343284.2866968984
       1.4551915228366852e-11
  -88751.3376134952
   55923.41773892664
 -343284.28669689794

18-element Vector{Float64}:
   68795.59015739957
  219962.82795589225
      -2.9103830456733704e-10
  343016.2478354882
  -68795.59015739936
  219962.82795589176
   37800.84159036354
   62812.02883954786
       8.87666828930378e-10
 -102574.80641287049
  -37800.841590364435
   62812.02883955106
  -58067.16527767509
 -353864.88032991503
       1.760781742632389e-9
  -92261.39435366755
   58067.165277673404
 -353864.88032991794

18-element Vector{Float64}:
   70788.54484113306
  226642.3403753821
       5.238689482212067e-10
  353080.86219338514
  -70788.5448411335
  226642.34037538245
   38928.51386185975
   64999.0546951131
       1.964508555829525e-9
 -105685.32704819806
  -38928.51386186163
   64999.054695112805
  -60231.37153898124
 -364431.532823378
       4.802132025361061e-10
  -95815.2596394211
   60231.37153898055
 -364431.53282337857

18-element Vector{Float64}:
   72777.14648894976
  233323.14381758973
       1.4551915228366852e-11
  363127.4556861862
  -72777.14648894976
  233323.14381758976
   40055.15229672351
   67202.0859581249
      -6.984919309616089e-10
 -108796.48440964957
  -40055.15229672256
   67202.08595812361
  -62415.77859811116
 -374984.2800723723
      -7.275957614183426e-11
  -99412.87068322118
   62415.77859811096
 -374984.28007237124

18-element Vector{Float64}:
   74761.47662965833
  240005.27333858854
      -1.4551915228366852e-11
  373156.1240745818
  -74761.4766296583
  240005.2733385885
   41180.75912555432
   69421.06431442112
      -5.456968210637569e-10
 -111908.32173082084
  -41180.75912555389
   69421.06431442022
  -64620.133088936294
 -385523.1561827547
      -3.7834979593753815e-10
 -103054.16528427122
   64620.13308893676
 -385523.15618275345

18-element Vector{Float64}:
   76741.61608046998
  246688.7634490651
      -1.4551915228366852e-11
  383166.96119608986
  -76741.61608046998
  246688.76344906504
   42305.33664823586
   71655.93145635919
       6.83940015733242e-10
 -115020.88217223076
  -42305.336648236305
   71655.93145635922
  -66844.18602432542
 -396048.19354125665
       4.94765117764473e-10
 -106739.08175219392
   66844.1860243247
 -396048.1935412571

18-element Vector{Float64}:
   78717.64496656542
  253373.64811759393
      -8.731149137020111e-11
  393160.0590266328
  -78717.64496656535
  253373.64811759396
   43428.887230219276
   73906.62907751685
      -2.9103830456733704e-11
 -118134.20881928393
  -43428.887230219145
   73906.62907751685
  -69087.69262400139
 -406559.4228827792
      -4.3655745685100555e-11
 -110467.5588320119
   69087.69262400131
 -406559.4228827793

18-element Vector{Float64}:
   80689.64274009634
  260059.96077382666
       1.4551915228366852e-11
  403135.50774023007
  -80689.64274009634
  260059.9607738267
   44551.413299135274
   76173.09886660642
       4.147295840084553e-10
 -121248.34468058369
  -44551.413299135624
   76173.09886660712
  -71350.41214947581
 -417056.87335507653
       3.4924596548080444e-10
 -114239.53563035924
   71350.41214947542
 -417056.87335507746

18-element Vector{Float64}:
   82657.68819861734
  266747.73431152746
       0.0
  413093.395766815
  -82657.68819861732
  266747.73431152746
   45672.91734165874
   78455.28250070458
       9.167706593871117e-10
 -124363.33268650614
  -45672.91734165941
   78455.28250070591
  -73632.10774568826
 -427540.5725809683
       1.3387762010097504e-9
 -118054.9515428358
   73632.10774568668
 -427540.57258097024

18-element Vector{Float64}:
   84621.85950296192
  273437.00109147996
       0.0
  423033.8098482785
  -84621.8595029619
  273437.00109147996
   46793.40190064332
   80753.12163781398
       1.7462298274040222e-10
 -127479.21568801283
  -46793.40190064307
   80753.12163781386
  -75932.54628902131
 -438010.5467182
      -1.7462298274040222e-10
 -121913.74618245312
   75932.5462890211
 -438010.5467182003

18-element Vector{Float64}:
   86582.23419459944
  280127.7929442683
       0.0
  432956.8350928588
  -86582.23419459941
  280127.79294426827
   47912.86957249657
   83066.55790883745
       5.311449058353901e-10
 -130596.03645566566
  -47912.86957249705
   83066.55790883879
  -78251.49824135995
 -448466.8205171376
       3.7834979593753815e-10
 -125815.85930912929
   78251.49824135948
 -448466.82051713904

18-element Vector{Float64}:
   88538.88921247039
  286820.14117291995
       7.275957614183426e-11
  442862.5550279364
  -88538.88921247034
  286820.14117291983
   49031.32300478533
   85395.53290898335
       1.4551915228366852e-11
 -133713.83767889708
  -49031.323004785416
   85395.5329089833
  -80588.73750989807
 -458909.41737636254
       0.0
 -129761.23076012064
   80588.73750989804
 -458909.4173763626

18-element Vector{Float64}:
   90491.90090931638
  293514.0765553929
      -8.149072527885437e-10
  452751.0516512663
  -90491.9009093157
  293514.07655539265
   50148.764894048036
   87739.98818867852
      -9.531504474580288e-10
 -136832.6619653671
  -50148.764894046835
   87739.98818867875
  -82944.04131241888
 -469338.3593963179
      -5.529727786779404e-10
 -133749.8003814065
   82944.04131241931
 -469338.3593963177

18-element Vector{Float64}:
   92441.34506753036
  300209.6293469435
      -4.3655745685100555e-10
  462622.40548080264
  -92441.34506753001
  300209.6293469424
   51265.19798382542
   90099.86524401
       3.128661774098873e-10
 -139952.55184053112
  -51265.19798382558
   90099.86524401221
  -85317.19004776377
 -479753.6674311252
       1.1641532182693481e-9
 -137781.5079599279
   85317.19004776253
 -479753.6674311265

18-element Vector{Float64}:
   94387.29691452993
  306906.8292823351
       1.4551915228366852e-11
  472476.6956031044
  -94387.29691452993
  306906.8292823351
   52380.62506286366
   92475.10550672689
      -2.6193447411060333e-10
 -143073.54974732173
  -52380.62506286333
   92475.10550672689
  -87707.96717126327
 -490155.36113862944
       2.0372681319713593e-10
 -141856.29315664782
   87707.967171263
 -490155.3611386295

18-element Vector{Float64}:
   96329.8311376679
  313605.70557791623
       1.4551915228366852e-11
  482313.9997204264
  -96329.8311376679
  313605.70557791623
   53495.048963507885
   94865.65033386572
      -2.1827872842550278e-11
 -146195.69804592198
  -53495.04896350765
   94865.6503338656
  -90116.15907488076
 -500543.45902883215
       3.2014213502407074e-10
 -145974.0954404037
   90116.1590748802
 -500543.4590288325

18-element Vector{Float64}:
   98269.02189869521
  320306.2869335471
      -5.820766091346741e-11
  492134.3941965515
  -98269.02189869525
  320306.28693354706
   54608.47256025521
   97271.44099699229
      -6.83940015733242e-10
 -149319.03901367943
  -54608.472560254486
   97271.44099699089
  -92541.55497185301
 -510917.9785107386
      -6.111804395914078e-10
 -150134.85402247435
   92541.55497185368
 -510917.9785107365

18-element Vector{Float64}:
  100204.94284778702
  327008.601534384
      -4.802132025361061e-10
  501937.95410139335
 -100204.94284778662
  327008.6015343831
   55720.89876847283
   99692.41867114377
      -3.4924596548080444e-10
 -152443.61484503452
  -55720.898768472245
   99692.41867114493
  -94983.94678561865
 -521278.9359377672
       2.9103830456733704e-11
 -154338.50779187994
   94983.94678561851
 -521278.93593776756

18-element Vector{Float64}:
  102137.66713713865
  333712.67705252167
      -2.9103830456733704e-11
  511724.7532544624
 -102137.66713713868
  333712.67705252167
   56832.33054326053
  102128.52442345233
       6.83940015733242e-10
 -155569.4676515605
  -56832.330543261014
  102128.52442345419
  -97443.12904284231
 -531626.3466517577
       4.94765117764473e-10
 -158584.99525133453
   97443.12904284168
 -531626.3466517598

18-element Vector{Float64}:
  104067.2674341531
  340418.54064849863
       0.0
  521494.86426722293
 -104067.26743415307
  340418.5406484986
   57942.77087845815
  104579.69920149416
       2.255546860396862e-10
 -158696.63946204126
  -57942.770878458294
  104579.69920149352
  -99918.89877034712
 -541960.225025671
       2.0372681319713593e-10
 -162874.25445382565
   99918.89877034686
 -541960.2250256701

18-element Vector{Float64}:
  105993.81593421167
  347126.2189726516
      -7.275957614183426e-11
  531248.3585843826
 -105993.81593421164
  347126.2189726516
   59052.22280577302
  107045.88382139592
       6.402842700481415e-10
 -161825.17222257232
  -59052.22280577368
  107045.88382139755
 -102411.05539578586
 -552280.5845050456
       5.529727786779404e-10
 -167206.2229398141
  102411.05539578533
 -552280.5845050472

18-element Vector{Float64}:
  107917.3843730549
  353835.7381663328
       8.87666828930378e-10
  540985.3065241829
 -107917.38437305564
  353835.7381663331
   60160.68939405103
  109527.01895573636
       8.149072527885437e-10
 -164955.10779668076
  -60160.689394051646
  109527.01895573537
 -104919.40065187763
 -562587.4376483107
       1.7462298274040222e-10
 -171580.83767501873
  104919.40065187716
 -562587.4376483103

18-element Vector{Float64}:
  109838.0440387781
  360547.12386299827
       8.87666828930378e-10
  550705.7773177184
 -109838.04403877887
  360547.1238629986
   61268.173748644076
  112023.04512120545
       1.0841176845133305e-9
 -168086.4879654892
  -61268.17374864527
  112023.0451212048
 -107443.73848407404
 -572880.796165955
      -4.0745362639427185e-10
 -175998.03498872631
  107443.73848407443
 -572880.7961659549

18-element Vector{Float64}:
  111755.86578343478
  367260.40118913446
      -4.3655745685100555e-11
  560409.8391473077
 -111755.86578343474
  367260.40118913446
   62374.67901089878
  114533.9026661354
       2.6921043172478676e-10
 -171219.35442782316
  -62374.679010899265
  114533.90266613691
 -109983.87496149006
 -583160.67095868
       4.656612873077393e-10
 -180457.7505126642
  109983.87496148983
 -583160.6709586815

18-element Vector{Float64}:
  113670.92003428371
  373975.594765078
       4.3655745685100555e-11
  570097.5591840164
 -113670.92003428367
  373975.59476507787
   63480.208357751515
  117059.5317578488
       1.673470251262188e-10
 -174353.74880034805
  -63480.20835775204
  117059.53175784845
 -112539.61819096954
 -593427.072154567
       4.3655745685100555e-10
 -184959.91912038787
  112539.61819096931
 -593427.0721545665

18-element Vector{Float64}:
  115583.27680466448
  380692.7287056803
       1.4551915228366852e-11
  579769.0036242856
 -115583.27680466448
  380692.72870568035
   64584.76500140578
  119599.87236984196
      -1.7462298274040222e-10
 -177489.7126176873
  -64584.765001405496
  119599.87236984196
 -115110.77823416912
 -603680.0091452664
       1.4551915228366852e-10
 -189504.47486711002
  115110.77823416887
 -603680.0091452665

18-element Vector{Float64}:
  117493.00570451964
  387411.82662084774
       8.440110832452774e-10
  589424.2377257727
 -117493.00570452034
  387411.8266208481
   65688.35218911964
  122154.8642689106
       1.367880031466484e-9
 -180627.2873324766
  -65688.35218912092
  122154.86426891037
 -117697.167027515
 -613919.4906213664
       3.7834979593753815e-10
 -194091.35093007958
  117697.16702751436
 -613919.4906213668

18-element Vector{Float64}:
  119400.1759505656
  394132.9116159559
      -1.0186340659856796e-10
  599063.3258423912
 -119400.17595056558
  394132.9116159555
   66790.97320306867
  124724.44700210856
      -1.5279510989785194e-10
 -183766.51431540772
  -66790.97320306866
  124724.44700210908
 -120298.59830493087
 -624145.5246068757
       1.7462298274040222e-10
 -198720.47954936133
  120298.59830493096
 -624145.5246068756

18-element Vector{Float64}:
  121304.85637612073
  400856.0062921235
      -5.820766091346741e-11
  608686.3314586075
 -121304.85637612066
  400856.0062921234
   67892.63136028816
  127308.5598836728
      -4.802132025361061e-10
 -186907.43485519578
  -67892.63136028756
  127308.55988367315
 -122914.88752323207
 -634358.1184929439
      -4.0745362639427185e-10
 -203391.79196911654
  122914.8875232324
 -634358.1184929439

18-element Vector{Float64}:
  123207.1154406031
  407581.1327463781
      -2.0372681319713593e-10
  618293.3172230059
 -123207.115440603
  407581.1327463779
   68993.33001269714
  129907.14198182558
      -4.729372449219227e-10
 -190050.0901585269
  -68993.33001269653
  129907.14198182902
 -125545.85179007161
 -644557.2790708105
       1.367880031466484e-9
 -208105.2183792648
  125545.85179007023
 -644557.2790708144

18-element Vector{Float64}:
  125107.02123869119
  414308.3125716873
      -4.656612873077393e-10
  627884.3449811728
 -125107.02123869085
  414308.312571687
   70093.07254719496
  132520.1321055771
       1.1641532182693481e-10
 -193194.5213499069
  -70093.07254719507
  132520.13210557937
 -128191.30979434508
 -654743.0125640788
       1.0477378964424133e-9
 -212860.68785763695
  128191.30979434408
 -654743.012564081

18-element Vector{Float64}:
  127004.64150916525
  421037.56685687596
      -3.2014213502407074e-10
  637459.4758079028
 -127004.6415091651
  421037.5668568759
   71191.86238581786
  135147.4687914279
      -1.1568772606551647e-9
 -196340.76947146287
  -71191.86238581681
  135147.46879142942
 -130851.0817389726
 -664915.3246602747
      -2.3283064365386963e-10
 -217658.128312499
  130851.08173897314
 -664915.3246602754

18-element Vector{Float64}:
  128900.04364342452
  427768.9161864178
       0.0
  647018.7700387532
 -128900.0436434245
  427768.9161864178
   72289.70298596207
  137789.09029010608
      -7.275957614183426e-11
 -199488.87548263
  -72289.70298596195
  137789.09029010625
 -133524.98927595152
 -675074.2205418214
       5.820766091346741e-11
 -222497.4664255281
  133524.98927595143
 -675074.2205418214

18-element Vector{Float64}:
  130793.29469370082
  434502.380640131
      -2.9103830456733704e-11
  656562.2873010112
 -130793.2946937008
  434502.38064013096
   73386.59784066935
  140444.93455323315
       5.020410753786564e-10
 -202638.88025981007
  -73386.5978406698
  140444.93455323437
 -136212.85544361608
 -685219.704916374
       3.4924596548080444e-10
 -227378.62759518123
  136212.85544361564
 -685219.7049163756

18-element Vector{Float64}:
  132684.46138095035
  441237.9797927395
      -4.656612873077393e-10
  666090.0865440357
 -132684.4613809501
  441237.9797927394
   74482.55047896574
  143114.93922003836
      -1.8189894035458565e-9
 -205790.82459588046
  -74482.55047896382
  143114.93922003894
 -138914.5046060129
 -695351.7820466148
      -5.529727786779404e-10
 -232301.53588048194
  138914.5046060136
 -695351.7820466146

18-element Vector{Float64}:
  134573.6101024517
  447975.73271334585
      -3.2014213502407074e-10
  675602.2260690338
 -134573.6101024514
  447975.7327133449
   75577.56446624064
  145799.04160404392
       4.3655745685100555e-11
 -208944.749199651
  -75577.5644662412
  145799.04160404543
 -141629.7623943359
 -705470.4557794833
       1.4551915228366852e-10
 -237266.11394519647
  141629.76239433634
 -705470.455779483

18-element Vector{Float64}:
  136460.80693910056
  454715.65796478925
       2.9103830456733704e-11
  685098.7635583021
 -136460.80693910056
  454715.6579647893
   76671.64340470263
  148497.17867981124
      -6.548361852765083e-10
 -212100.69469518264
  -76671.6434047019
  148497.17867980927
 -144358.4556503252
 -715575.7295749285
      -6.402842700481415e-10
 -242272.28300246334
  144358.45565032578
 -715575.7295749267

18-element Vector{Float64}:
  138346.11766241203
  461457.77360290784
      -5.820766091346741e-11
  694579.7561039056
 -138346.11766241209
  461457.7736029078
   77764.79093383832
  151209.28706968122
      -7.130438461899757e-10
 -215258.70162102833
  -77764.79093383806
  151209.28706968157
 -147100.41237159487
 -725667.6065341432
      -2.9103830456733704e-10
 -247319.96275976996
  147100.41237159568
 -725667.6065341425

18-element Vector{Float64}:
  140229.6077412253
  468202.0971756914
       2.9103830456733704e-11
  704045.2602358581
 -140229.60774122534
  468202.0971756914
   78857.01073095808
  153935.30303062615
      -8.003553375601768e-11
 -218418.81042931633
  -78857.01073095817
  153935.30303062598
 -149855.46165880133
 -735746.0894273836
       0.0
 -252409.07136440987
  149855.46165880153
 -735746.0894273832

18-element Vector{Float64}:
  142111.3423481287
  474948.6457223579
       8.731149137020111e-11
  713495.3319498133
 -142111.3423481287
  474948.64572235785
   79948.30651174816
  156675.16244108195
      -1.8917489796876907e-10
 -221581.06148478563
  -79948.30651174807
  156675.16244108137
 -152623.43366461288
 -745811.1807213083
      -2.0372681319713593e-10
 -257539.52534929052
  152623.43366461303
 -745811.1807213079

18-element Vector{Float64}:
  143991.38636559783
  481697.43577232334
       1.4551915228366852e-10
  722930.0267342529
 -143991.38636559795
  481697.4357723225
   81038.68203086416
  159428.8007879167
       9.604264050722122e-10
 -224745.49506362402
  -81038.68203086546
  159428.80078791914
 -155404.15954441135
 -755862.8826059452
       2.9103830456733704e-10
 -262711.2395792185
  155404.1595444114
 -755862.8826059466

18-element Vector{Float64}:
  145869.80439185468
  488448.483344092
       0.0
  732349.3995972212
 -145869.80439185465
  488448.483344092
   82128.14108257668
  162196.15315345064
       1.2369127944111824e-10
 -227912.15135220755
  -82128.14108257667
  162196.15315345064
 -158197.47140868363
 -765901.1970212521
       0.0
 -267924.1271975942
  158197.47140868343
 -765901.1970212524

18-element Vector{Float64}:
  147746.66074644652
  495201.80394405907
       0.0
  741753.5050926136
 -147746.6607464465
  495201.8039440592
   83216.6875014236
  164977.15420256625
      -5.602487362921238e-10
 -231081.07044572907
  -83216.68750142318
  164977.15420256613
 -161003.20227704474
 -775926.1256833012
      -3.7834979593753815e-10
 -273178.09957353334
  161003.2022770453
 -775926.1256833009

18-element Vector{Float64}:
  149622.01947555935
  501957.4125652396
       2.9103830456733704e-11
  751142.3973460139
 -149622.01947555927
  501957.41256523953
   84304.3251629007
  167771.73816993646
      -3.92901711165905e-10
 -234252.29234665877
  -84304.32516290064
  167771.73816993565
 -163821.18603385804
 -785937.670110126
      -2.3283064365386963e-10
 -278473.0662494553
  163821.1860338584
 -785937.670110125

18-element Vector{Float64}:
  151495.94435705047
  508715.3236859085
      -2.9103830456733704e-11
  760516.1300801111
 -151495.94435705044
  508715.32368590846
   85391.05798417827
  170579.8388473494
       4.0745362639427185e-10
 -237425.8569630761
  -85391.05798417922
  170579.83884735126
 -166651.2573853909
 -795935.8316472166
       6.984919309616089e-10
 -283808.93488911807
  166651.2573853907
 -795935.8316472181

18-element Vector{Float64}:
  153368.49890522528
  515475.55126818724
       0.0
  769874.7566397204
 -153368.49890522528
  515475.55126818724
   86476.88992484222
  173401.3895711822
      -1.3096723705530167e-10
 -240601.8041068639
  -86476.88992484227
  173401.3895711823
 -169493.25181847558
 -805920.611492732
       8.731149137020111e-11
 -289185.61122613173
  169493.2518184757
 -805920.6114927318

18-element Vector{Float64}:
  155239.74637533943
  522238.10875654384
      -5.820766091346741e-11
  779218.3300163746
 -155239.7463753394
  522238.10875654395
   87561.82498765292
  176236.32320997247
      -6.039044819772243e-10
 -243780.17349173455
  -87561.82498765188
  176236.32320997096
 -172347.00556064036
 -815892.0107223572
      -4.94765117764473e-10
 -294602.9990129586
  172347.00556064042
 -815892.0107223557

18-element Vector{Float64}:
  157109.74976784576
  529003.0090762418
       5.820766091346741e-11
  788546.902872545
 -157109.74976784573
  529003.009076242
   88645.86721931587
  179084.57215216267
       2.255546860396862e-10
 -246961.00473113393
  -88645.86721931605
  179084.57215216372
 -175212.35554165835
 -825850.0303139145
       5.820766091346741e-11
 -300060.9999703907
  175212.35554165827
 -825850.0303139159

18-element Vector{Float64}:
  158978.5718323777
  535770.2646317208
      -2.9103830456733704e-11
  797860.5275654717
 -158978.57183237773
  535770.2646317208
   89729.0207112857
  181946.06829399522
       7.785274647176266e-10
 -250144.33733595806
  -89729.02071128643
  181946.06829399557
 -178089.1393564895
 -835794.6711716882
      -1.1641532182693481e-10
 -305559.51373756904
  178089.1393564896
 -835794.6711716886

18-element Vector{Float64}:
  160846.27507148037
  542539.8873049268
      -4.0745362639427185e-10
  807159.256170634
 -160846.27507147985
  542539.8873049266
   90811.28960056847
  184820.74302755517
       1.7462298274040222e-10
 -253330.21071214555
  -90811.28960056901
  184820.7430275546
 -180977.1952295819
 -845725.9341504723
      -4.3655745685100555e-10
 -311098.43782250804
  180977.1952295826
 -845725.9341504712

18-element Vector{Float64}:
  162712.92174407985
  549311.8884535868
       2.9103830456733704e-11
  816443.1405048403
 -162712.92174407988
  549311.8884535868
   91892.67807054005
  187708.52722900175
      -1.673470251262188e-10
 -256518.66415809054
  -91892.6780705398
  187708.52722900175
 -183876.3619804972
 -855643.8200793777
      -2.3283064365386963e-10
 -316677.66755317163
  183876.36198049734
 -855643.8200793776

18-element Vector{Float64}:
  164578.5738687142
  556086.2789094419
       5.820766091346741e-11
  825712.2321489821
 -164578.57386871433
  556086.2789094418
   92973.19035178532
  190609.35124698468
      -1.1641532182693481e-9
 -259709.7368618796
  -92973.19035178417
  190609.35124698363
 -186786.4789908267
 -865548.3297854082
      -4.0745362639427185e-10
 -322297.09602913936
  186786.47899082722
 -865548.3297854066

18-element Vector{Float64}:
  166443.29322649672
  562863.0689764282
       0.0
  834966.5824704245
 -166443.29322649672
  562863.0689764284
   94052.83072293072
  193523.14489124203
      -5.893525667488575e-10
 -262903.4678983877
  -94052.83072293003
  193523.14489124075
 -189707.3861723797
 -875439.4641167806
      -5.529727786779404e-10
 -327956.6140738169
  189707.38617238015
 -875439.4641167786

18-element Vector{Float64}:
  168307.14136384625
  569642.2684288318
       5.238689482212067e-10
  844206.2426450684
 -168307.14136384663
  569642.2684288322
   95131.60351148935
  196449.8374214106
       1.5570549294352531e-9
 -266099.8962262089
  -95131.60351149095
  196449.83742141013
 -192638.92393661407
 -885317.2239660359
       4.0745362639427185e-10
 -333656.11018727237
  192638.92393661366
 -885317.2239660361

18-element Vector{Float64}:
  170170.17959496562
  576423.8865093944
      -4.656612873077393e-10
  853431.2636790646
 -170170.17959496524
  576423.8865093944
   96209.51309471474
  199389.35753605235
      -3.92901711165905e-10
 -269299.06068437436
  -96209.51309471423
  199389.357536052
 -195580.93316527287
 -895181.6102929389
      -4.656612873077393e-10
 -339395.4704997059
  195580.93316527337
 -895181.6102929384

18-element Vector{Float64}:
  172032.46900407644
  583207.9319274053
      -3.7834979593753815e-10
  862641.6964302135
 -172032.46900407595
  583207.9319274051
   97286.56390044958
  202341.6333618951
       1.8917489796876907e-9
 -272500.9999889499
  -97286.56390045179
  202341.63336189708
 -198533.25518222206
 -905032.6241471565
       1.367880031466484e-9
 -345174.57872555044
  198533.25518222095
 -905032.6241471593

18-element Vector{Float64}:
  173894.0704474144
  589994.412856755
       2.9103830456733704e-10
  871837.5916290268
 -173894.07044741462
  589994.4128567551
   98362.76040798523
  205306.59244331508
       8.149072527885437e-10
 -275705.7527294153
  -98362.76040798631
  205306.59244331403
 -201495.73172644552
 -914870.2666907487
       1.4551915228366852e-10
 -350993.3161182544
  201495.73172644555
 -914870.2666907478

18-element Vector{Float64}:
  175755.04455498996
  596783.3369339851
       2.9103830456733704e-11
  881018.9998994911
 -175755.04455499005
  596783.3369339848
   99438.10714890808
  208284.1617320386
      -7.275957614183426e-11
 -278913.35736491194
  -99438.10714890817
  208284.16173203907
 -204468.2049261995
 -924694.5392204393
       8.731149137020111e-11
 -356851.5614257482
  204468.2049261996
 -924694.5392204389

18-element Vector{Float64}:
  177615.45173209763
  603574.7112562971
      -5.820766091346741e-11
  890185.9717794829
 -177615.4517320976
  603574.7112562967
  100512.60870795345
  211274.26757714723
       5.093170329928398e-11
 -282123.8522202558
 -100512.60870795367
  211274.2675771478
 -207450.51727427955
 -934505.4431897358
       1.7462298274040222e-10
 -362749.190846644
  207450.51727427953
 -934505.4431897361

18-element Vector{Float64}:
  179475.35216060575
  610368.5423795824
       0.0
  899338.5577409067
 -179475.35216060575
  610368.5423795824
  101586.26972385413
  214276.83571527712
       1.0695657692849636e-9
 -285337.27548181923
 -101586.26972385524
  214276.83571527922
 -210442.5116044047
 -944302.9802308191
       1.5425030142068863e-9
 -368686.07798716764
  210442.51160440323
 -944302.9802308221

18-element Vector{Float64}:
  181334.8058000035
  617164.8363164193
      -4.656612873077393e-10
  908476.8082094993
 -181334.80580000315
  617164.8363164179
  102659.09489018103
  217291.79126114817
      -6.83940015733242e-10
 -288553.6651932057
 -102659.09489018045
  217291.7912611491
 -213444.0310686835
 -954087.1521762807
      -1.7462298274040222e-10
 -374662.0938188676
  213444.03106868375
 -954087.1521762797

18-element Vector{Float64}:
  183193.87238822033
  623963.5985340825
       0.0
  917600.7735843494
 -183193.87238822033
  623963.5985340824
  103731.08895617037
  220319.0586983387
      -3.4924596548080444e-10
 -291773.05925075006
 -103731.08895616987
  220319.0586983374
 -216454.9191161585
 -963857.9610806601
      -3.2014213502407074e-10
 -380677.1066371216
  216454.9191161587
 -963857.9610806584

18-element Vector{Float64}:
  185052.6114422143
  630764.833952559
      -2.9103830456733704e-10
  926710.5042570936
 -185052.61144221405
  630764.8339525588
  104802.25672755751
  223358.5618703526
      -1.2332748156040907e-9
 -294995.4953988408
 -104802.25672755612
  223358.56187035225
 -219475.01947239792
 -973615.4092418116
      -3.4924596548080444e-10
 -386730.9820204535
  219475.01947239827
 -973615.4092418106

18-element Vector{Float64}:
  186911.0822583321
  637568.5469425633
      -3.7834979593753815e-10
  935806.0506308277
 -186911.08225833176
  637568.5469425616
  105872.60306738754
  226410.22397201776
      -9.1313268058002e-10
 -298221.0112250338
 -105872.6030673869
  226410.22397201997
 -222504.17612012825
 -983359.4992221101
      -2.3283064365386963e-10
 -392823.58279073617
  222504.17612012883
 -983359.4992221104

18-element Vector{Float64}:
  188769.34391244577
  644374.7413235696
       3.4924596548080444e-10
  944887.4631387056
 -188769.34391244603
  644374.7413235698
  106942.13289681928
  229473.96754116018
       1.1314114090055227e-9
 -301449.6441550043
 -106942.13289682046
  229473.96754115936
 -225542.23328089516
 -993090.2338694606
      -2.3283064365386963e-10
 -398954.7689742399
  225542.23328089534
 -993090.23386946

18-element Vector{Float64}:
  190627.45525986547
  651183.4203618722
       0.0
  953954.7922622492
 -190627.45525986544
  651183.420361872
  108010.85119591115
  232549.71445059066
      -2.473825588822365e-10
 -304681.4314473193
 -108010.85119591077
  232549.71445058996
 -228589.03539772925
      -1.0028076163381257e6
      -2.9103830456733704e-10
 -405124.3977636048
  228589.0353977294
      -1.0028076163381247e6

18-element Vector{Float64}:
  192485.4749350269
  657994.5867686529
       0.0
  963008.0885493524
 -192485.4749350269
  657994.5867686529
  109078.76300439713
  235637.38590046437
       3.41970007866621e-10
 -307916.410187989
 -109078.76300439725
  235637.38590046496
 -231644.42711881053
      -1.0125116501094176e6
       1.1641532182693481e-10
 -411332.32348076266
  231644.42711881016
      -1.0125116501094188e6

18-element Vector{Float64}:
  194343.46135096689
  664808.2426981002
      -4.0745362639427185e-10
  972047.4026320002
 -194343.46135096648
  664808.2426980993
  110145.87342244963
  238736.9024109284
      -3.055902197957039e-10
 -311154.6172848732
 -110145.87342244915
  238736.90241092967
 -234708.25328211463
      -1.0222023390121844e6
      -1.1641532182693481e-10
 -417578.397540816
  234708.2532821146
      -1.0222023390121843e6

18-element Vector{Float64}:
  196201.47269857148
  671624.389745534
       4.3655745685100555e-10
  981072.7852436713
 -196201.47269857192
  671624.3897455335
  111212.18761141079
  241848.18381514843
       1.0331859812140465e-9
 -314396.08946187224
 -111212.18761141221
  241848.18381515075
 -237780.35890103248
      -1.0318796872431212e6
       2.3283064365386963e-10
 -423862.4684169216
  237780.35890103268
      -1.0318796872431223e6

18-element Vector{Float64}:
  198059.56694561886
  678443.0289455972
       2.9103830456733704e-11
  990084.2872364572
 -198059.56694561892
  678443.0289455975
  112277.71079452193
  244971.149252675
       3.310560714453459e-10
 -317640.8632529323
 -112277.71079452231
  244971.14925267594
 -240860.58915094583
      -1.0415436993869257e6
       8.731149137020111e-10
 -430184.3816062182
  240860.58915094496
      -1.041543699386927e6