In [1]:
using LinearAlgebra, Plots, LaTeXStrings, Symbolics

In [2]:
include("ModuloFunciones.jl")
F = ModuloFunciones

Main.ModuloFunciones

In [3]:
const E = 2.1E06
const ν = 0.3

# Problema de deformación plana.
global C = ((1 - ν) / ((1 + ν) * (1 - ν))) * E * [1 (ν/(1-ν)) 0; (ν/(1-ν)) 1 0; 0 0 ((1-2*ν)/(2*(1-ν)))];

In [4]:
begin
    const longx = 3.0
    const longy = 3.0

    const numNodosx = 3
    const numNodosy = 3

    global  numNodosG = numNodosx * numNodosy

    # En el caso de elasticidad bidimensional se tiene 2 grados de libertad por nodo
    global GDLG = numNodosG * 2  

    global numElementos = (numNodosx - 1) * (numNodosy - 1)

    # F.mallador. Crea una malla de lementos rectangulares y define las coordenadas de sus nodos
    mGCoorNodales = F.mallador(numNodosx, numNodosy, longx, longy, numElementos)
    display(mGCoorNodales)

    # F.matrizConectividadGlobal --> Rutina que genera la conectividad global
    mConectG = F.matrizConectividadGlobal(numNodosx, numNodosy, numElementos)
    display(mConectG)

    # F.matrizGdGL --> Rutina que genera la matriz de grados de libertad global
    mGdlG = F.matrizGdGL(numNodosx, numNodosy, mConectG)
    #display(mGdlG)
end;


9×2 Matrix{Float64}:
 0.0  0.0
 1.5  0.0
 3.0  0.0
 0.0  1.5
 1.5  1.5
 3.0  1.5
 0.0  3.0
 1.5  3.0
 3.0  3.0

4×4 Matrix{Int64}:
 5  4  1  2
 6  5  2  3
 8  7  4  5
 9  8  5  6

In [5]:
begin
    @variables r s
    global Dr = Differential(r)
    global Ds = Differential(s)

    nFI = 4 # nFI --> Numero de funciones de interpolación

    h₁ = 1 / 4 * (1 + r) * (1 + s)
    h₂ = 1 / 4 * (1 - r) * (1 + s)
    h₃ = 1 / 4 * (1 - r) * (1 - s)
    h₄ = 1 / 4 * (1 + r) * (1 - s)

    global H = [h₁ h₂ h₃ h₄]
    global ∇H = [transpose([expand_derivatives(Dr(H[i])) for i in 1:nFI])
                transpose([expand_derivatives(Ds(H[i])) for i in 1:nFI])]
end

2×4 Matrix{Num}:
 0.25(1 + s)  -0.25(1 + s)  -0.25(1 - s)   0.25(1 - s)
 0.25(1 + r)   0.25(1 - r)  -0.25(1 - r)  -0.25(1 + r)

In [6]:
# Puntos de Gauss para itegración
begin
    nNodosInt = 9
    GL9Q = [-sqrt(0.6) -sqrt(0.6); 0 -sqrt(0.6); sqrt(0.6) -sqrt(0.6); sqrt(0.6) 0; sqrt(0.6) sqrt(0.6);
            0 sqrt(0.6); -sqrt(0.6) sqrt(0.6); -sqrt(0.6) 0; 0 0]

    wGL9Q = [5/9 5/9; 8/9 5/9; 5/9 5/9; 5/9 8/9; 5/9 5/9; 8/9 5/9; 5/9 5/9; 5/9 8/9; 8/9 8/9]
end;


In [7]:
 #                                 ***** ITERACION CERO *****

 begin
    #KG --> KG lineal. KG = KGL00 en esta iteración
    
    KG = F.KGL00(∇H, mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q)

    RG = zeros(GDLG)
    RG[14] = 3000
    RG[18] = 3000

    # Caso 2 (4 Elementos)
    # Imponemos condiciones de contorno de Dirichlet
    # U1x=0 => U1=0
    KG[1, :] .= 0
    KG[:, 1] .= 0
    KG[1, 1] = 1
    # U1y=0 => U2=0
    KG[2, :] .= 0
    KG[:, 2] .= 0
    KG[2, 2] = 1
    # U3y=0 => U6=0
    KG[6, :] .= 0
    KG[:, 6] .= 0
    KG[6, 6] = 1

    U₀ = KG \ RG

    for i in eachindex(U₀) if(abs(U₀[i]) <= 1E-10) U₀[i] = 0 end end

    display(U₀)
 end 

18-element Vector{Float64}:
  0.0
  0.0
 -0.002213095238095248
  0.006190476190476196
 -0.00442619047619049
  0.0
 -0.0024761904761904925
  0.005370238095238097
 -0.0022130952380952523
  0.0053702380952381
 -0.0019500000000000147
  0.005370238095238098
  0.0
  0.010740476190476193
 -0.002213095238095256
  0.004550000000000004
 -0.004426190476190494
  0.010740476190476194

In [8]:
mGdlE = mGdlG[:, 2]
display(U₀[mGdlE])
Uₑ = transpose(reshape(U₀[mGdlE], 2, 4))

8-element Vector{Float64}:
 -0.0019500000000000147
  0.005370238095238098
 -0.0022130952380952523
  0.0053702380952381
 -0.002213095238095248
  0.006190476190476196
 -0.00442619047619049
  0.0

4×2 transpose(::Matrix{Float64}) with eltype Float64:
 -0.00195     0.00537024
 -0.0022131   0.00537024
 -0.0022131   0.00619048
 -0.00442619  0.0

In [12]:
#=
it = 0
#KGLOBAL = zeros(GDLG, GDLG)
KG = zeros(GDLG, GDLG)
RA = zeros(GDLG)
RG = zeros(GDLG)
RG[14] = 3000
RG[18] = 3000
RA = zeros(GDLG)
Ui = U₀
ΔU = 0

FGA = F.FGA(U₀, GDLG, H, ∇H, numElementos, mGdlG, mGCoorNodales, mConectG, C, GL9Q, wGL9Q)

while it <= 10

    KGL0 = F.KGL00(∇H, mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q)
    KGL1 = F.KGL1(∇H, mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, Ui)
    KGL = KGL0 + KGL1
    KGNL = F.KGNL(mConectG, mGCoorNodales, C, numElementos, GDLG, mGdlG, GL9Q, wGL9Q, Ui, H, ∇H)

    KG =  KGL + KGNL 
    
    
    RA = RG - FGA
    
    #RA = zeros(GDLG)
    RA[14] = 3000
    RA[18] = 3000
    #display(RA)

    KG[1, :] .= 0
    KG[:, 1] .= 0
    KG[1, 1] = 1

    # U1y=0 => U2=0
    KG[2, :] .= 0
    KG[:, 2] .= 0
    KG[2, 2] = 1

    # U3y=0 => U6=0
    KG[6, :] .= 0
    KG[:, 6] .= 0
    KG[6, 6] = 1   
    #display(KG)
    

    ΔU = KG \ RA
    Ui +=  ΔU    # OJO REVISAR CUIDADOSAMENTE
    FGA = F.FGA(Ui, GDLG, H, ∇H, numElementos, mGdlG, mGCoorNodales, mConectG, C, GL9Q, wGL9Q)
    display(Ui)
it += 1

end
=#


In [17]:
U = U₀
KGLOBAL(numElementos, mGdlG, U, ∇H, mGCoorNodales, mConectG, C, GL9Q, wGL9Q)

UndefVarError: UndefVarError: `KEL0` not defined

In [11]:
(sqrt(16) - sqrt(4)) * 2^4 + 4^4 / 4^2

48.0