In [4]:
using LinearAlgebra, LaTeXStrings, Symbolics 

In [14]:
@variables Z₁, Z₂, Z₃, λ, t

5-element Vector{Num}:
 Z₁
 Z₂
 Z₃
  λ
  t

In [4]:
θ₁ = sqrt(Z₁^2 + Z₂^2 + Z₃^2)

sqrt(Z₁^2 + Z₂^2 + Z₃^2)

In [5]:
θ₂ = atan(sqrt(Z₁^2 + Z₂^2) / Z₃)

atan(sqrt(Z₁^2 + Z₂^2) / Z₃)

In [12]:
θ₃ = atan(Z₂ / Z₁)

atan(Z₂ / Z₁)

In [13]:
DZ1 = Differential(Z₁)
DZ2 = Differential(Z₂)
DZ3 = Differential(Z₃)

(::Differential) (generic function with 3 methods)

In [14]:
∂θ1∂Z1 = simplify(expand_derivatives(DZ1(θ₁)))

Z₁ / sqrt(Z₁^2 + Z₂^2 + Z₃^2)

In [15]:
∂θ1∂Z2 = expand_derivatives(DZ2(θ₁))

Z₂ / sqrt(Z₁^2 + Z₂^2 + Z₃^2)

In [16]:
∂θ1∂Z3 = expand_derivatives(DZ3(θ₁))

Z₃ / sqrt(Z₁^2 + Z₂^2 + Z₃^2)

In [20]:
∂θ2∂Z1 = simplify(expand_derivatives(DZ1(θ₂)))

(Z₁*Z₃) / ((Z₃^2 + sqrt(Z₁^2 + Z₂^2)^2)*sqrt(Z₁^2 + Z₂^2))

In [21]:
∂θ2∂Z2 = simplify(expand_derivatives(DZ2(θ₂)))

(Z₂*Z₃) / ((Z₃^2 + sqrt(Z₁^2 + Z₂^2)^2)*sqrt(Z₁^2 + Z₂^2))

In [22]:
∂θ2∂Z3 = simplify(expand_derivatives(DZ3(θ₂)))

(-sqrt(Z₁^2 + Z₂^2)) / (Z₃^2 + sqrt(Z₁^2 + Z₂^2)^2)

In [23]:
∂θ3∂Z1 = simplify(expand_derivatives(DZ1(θ₃)))

(-Z₂) / (Z₁^2 + Z₂^2)

In [24]:
∂θ3∂Z2 = simplify(expand_derivatives(DZ2(θ₃)))

Z₁ / (Z₁^2 + Z₂^2)

In [25]:
∂θ3∂Z3 = simplify(expand_derivatives(DZ3(θ₃)))

0

In [7]:

p(λ)=(2-λ) * (1-λ) + 3
expand(p(λ))

5 - 3λ + λ^2

In [12]:
expand((1-λ) * (1-λ) * (2-λ) + 2 + 1 -(1-λ) + (1-λ) - 2 * (1-λ))

3 - 3λ + 4(λ^2) - (λ^3)

In [16]:
a1 = expand((t+4//3)^3)

(64//27) + (16//3)*t + (4//1)*(t^2) + t^3

In [17]:
a2 = expand(-4 * (t + 4//3)^2)

-(64//9) - (32//3)*t - (4//1)*(t^2)

In [18]:
a3 = expand(3 * (t + 4//3))

(4//1) + (3//1)*t

In [20]:
expand(a1 + a2 + a3 - 3)

-(101//27) - (7//3)*t + t^3

In [63]:
a = 1
b = -4
c = 7
d = -9

-9

In [64]:
p1 = (3 * a * c - b^2) // (3 * a^2)

5//3

In [65]:
q = (2 * b^3 - 9 * a * b * c + 27 * a^2 * d) // (27 * a^3)

-119//27

In [66]:
Δ = q^2 + 4 * (p1 / 3)^3

181//9

In [67]:
u = cbrt((-q + sqrt(Δ)) / 2)

1.6443300183006742

In [68]:
v = cbrt((-q - sqrt(Δ)) / 2)

-0.33786134740135215

In [69]:
x1 = u + v - b // (3 * a)

2.6398020042326555

In [70]:
x2 = ((-1 / 2) * (u + v) - b / (3 * a)) + (sqrt(3) / 2 * (u - v))im 

0.6800989978836722 + 1.716628077860125im

In [71]:
x2 = ((-1 / 2) * (u + v) - b / (3 * a)) - (sqrt(3) / 2 * (u - v))im

0.6800989978836722 - 1.716628077860125im

In [72]:
A  = [8-λ 3 0; 3 4-λ 0; 0 0 1-λ]

3×3 Matrix{Num}:
 8 - λ      3      0
     3  4 - λ      0
     0      0  1 - λ

In [58]:
expand(det(A))

23 - 35λ + 13(λ^2) - (λ^3)

In [73]:
a = 1
b = -13
c = 35
d = -23

-23

In [74]:
p1 = (3 * a * c - b^2) // (3 * a^2)

-64//3

In [75]:
q = (2 * b^3 - 9 * a * b * c + 27 * a^2 * d) // (27 * a^3)

-920//27

In [76]:
Δ = q^2 + 4 * (p1 / 3)^3

-832//3

In [77]:
θ = acos(3 * q / (2 * p1) * sqrt(-3 / p1))

0.45459827201619835

In [81]:
x1 = 2 * sqrt(-p1 / 3) * cos(θ / 3) - b / (3 * a)

9.605551275463988

In [82]:
x2 = 2 * sqrt(-p1 / 3) * cos((θ + 2 * pi) / 3) - b / (3 * a)

1.0

In [85]:
x3 = 2 * sqrt(-p1 / 3) * cos((θ + 4 * pi) / 3) - b / (3 * a)

2.3944487245360118

In [95]:
(-2 - sqrt(13)) / 3

-1.8685170918213299

In [96]:
-28 / 15

-1.8666666666666667

In [94]:
-5 + sqrt(13)

-1.3944487245360109

In [99]:
X₀ = Matrix(I, 3, 3)
A = [8 3 0; 3 4 0; 0 0 1]
inv(A)

3×3 Matrix{Float64}:
  0.173913  -0.130435  -0.0
 -0.130435   0.347826  -0.0
  0.0        0.0        1.0

In [117]:
it = 1
A = [8 3 0; 3 4 0; 0 0 1]
X₀ = Matrix(I, 3, 3)
X₁ = zeros(3,3)
while (it < 10 )
    X₁ = 1/ 2 * ( X₀ + A * inv(X₀))
    C = X₁ * inv(X₀)
    #display(X₁)
    X₀ = X₁
    #(abs.(X₁ * inv(X₀)) <= 1e-03 * (I, 3, 3)) ? break : X₀ = X₁
   it += 1 
end
display(X₁)

3×3 Matrix{Float64}:
 2.75376   0.645622  0.0
 0.645622  1.89293   0.0
 0.0       0.0       1.0

In [116]:
X₁ * X₁

3×3 Matrix{Float64}:
 8.0  3.0  0.0
 3.0  4.0  0.0
 0.0  0.0  1.0

In [114]:
BB = [3.542 -sqrt(-sqrt(21853 / 81) + 154 / 9) 0; 0.831 sqrt(-sqrt(13) + 6) 0; 0 0 1]

3×3 Matrix{Float64}:
 3.542  -0.828144  0.0
 0.831   1.5474    0.0
 0.0     0.0       1.0

In [115]:
BB * BB

3×3 Matrix{Float64}:
 11.8576   -4.21476  0.0
  4.22929   1.70626  0.0
  0.0       0.0      1.0

In [140]:
P = [0 1 1; 0 (-2 + sqrt(13))/3 (-2 - sqrt(13))/3; 1 0 0]

3×3 Matrix{Float64}:
 0.0  1.0        1.0
 0.0  0.535184  -1.86852
 1.0  0.0        0.0

In [144]:
D = [1 0 0; 0 sqrt(6 + sqrt(13)) 0; 0 0 sqrt(6 - sqrt(13))]

3×3 Matrix{Float64}:
 1.0  0.0      0.0
 0.0  3.09928  0.0
 0.0  0.0      1.5474

In [145]:
B2 = P * D * inv(P)

3×3 Matrix{Float64}:
 2.75376   0.645622  0.0
 0.645622  1.89293   0.0
 0.0       0.0       1.0

In [146]:
B2 * B2

3×3 Matrix{Float64}:
 8.0  3.0  0.0
 3.0  4.0  0.0
 0.0  0.0  1.0